language: cpp
matrix:
  include:
    - os: linux
      dist: focal
      env: LIBTORRENT_BRANCH=RC_2_0
    - os: linux
      dist: focal
      env: LIBTORRENT_BRANCH=RC_1_2
    - os: linux
      dist: focal
      env: LIBTORRENT_BRANCH=RC_1_1
env:
  global:
    - MAKEFLAGS=-j2
    - PKG_CONFIG_PATH=/tmp/lib/pkgconfig
    - LD_LIBRARY_PATH=/tmp/lib
addons:
  apt:
    packages:
      - libboost-all-dev
      - libfuse-dev
      - libcurl4-openssl-dev
install:
  - env CXXFLAGS="-fpermissive -w" ./scripts/build-libtorrent $LIBTORRENT_BRANCH /tmp
script:
  - autoreconf -i && ./configure && make && make test
